---

- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
  tags:
    - environment-setup
    - database
    - mongo

- name: install mongoDB
  apt: 
    name: mongodb
    state: present
  notify:
    - start mongodb
  tags:
    - environment-setup
    - database
    - mongo

- name: copy config file
  copy:
    src: mongodb.conf
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb
  tags:
    - environment-setup
    - database
    - mongo

- name: Ensure mongodb is running and and enabled to start automatically on reboots
  systemd:
    name: mongodb
    enabled: yes
    state: started
  tags:
    - environment-setup
    - database
    - mongo
